@startuml

entity Material
entity Repository
entity User
entity Tag
control Search
control Filter
boundary "Search bar" as sbar
boundary "Search filters" as sfil
boundary "Search button" as sbut


Filter -up-> sfil

Search -left-> Filter
Search -up-> sbar
Search -up-> sbut 

Search --> Repository
Search --> User

User --> Tag

Repository --> Tag
Repository --> Material
@enduml
