@startuml
left to right direction
allowmixing

cloud BlueBerryServer <<hostname>>

class UserController {
  ..
  <<GET>> Get (id : integer) : UserDTO
  <<PUT>> UpdateTags (id : integer, tags : IEnumerable<string>) : IActionResult 
}

class MaterialController {
  ..
  <<GET>> Get (Tag : string, Keywords : string, StartYear : int, EndYear : int) : IEnumerable<MaterialDTO>
}

class TagController {
  ..
  <<GET>> Get () : IEnumerable<TagDTO>
}
label "api/material?{query}" as material

label "api/tag" as tag

label "api/user/{id}" as userid

BlueBerryServer -. material
material -.> MaterialController::Get 

BlueBerryServer -. tag
tag -.> TagController::Get


BlueBerryServer -. userid
userid -.> UserController::Get   
userid -.> UserController::UpdateTags

@enduml
