@startuml
left to right direction
allowmixing

cloud Server <<https://hostname>>

class UserController {
  ..
  <<GET>> Get (id : integer) : UserDto
  <<PUT>> Put (id : integer, user : UserUpdateDto) : IActionResult 
  <<POST>> Post (id : integer, user : UserCreateDto) : ActionResult<UserDto>
}

class MaterialController {
  ..
  <<GET>> Get (searchString : string?, tags : string?, startYear : int?, endYear : int?,
               type : string?, offset : int, limit : int, sortby : string?, userid : int?) : ActionResult<IEnumerable<MaterialDto>>
}

class TagController {
  ..
  <<GET>> Get () : IEnumerable<TagDto>
}
label "api/material?{query}" as material

label "api/tag" as tag

label "api/user/{id}" as userid

Server -. material
material -.> MaterialController::Get 

Server -. tag
tag -.> TagController::Get


Server -. userid
userid -.> UserController::Get   
userid -.> UserController::Put
userid -.> UserController::Post

@enduml
