@startuml
left to right direction
allowmixing

cloud BlueBerryServer <<hostname>>

class UserController {
  ..
  <<GET>> Get (id : integer) : UserDTO
  <<PUT>> UpdateTags (id : integer, tags : IEnumerable<TagDTO>) : IActionResult 
}

class MaterialController {
  ..
  <<GET>> Get (Tag : string, Keywords : string, StartYear : int, EndYear : int) : IEnumerable<MaterialDTO>
}

class TagController {
  ..
  <<GET>> Get () : IEnumerable<TagDTO>
}
label "/material?{query}" as material

label "/tag" as tag

label "/user/{id}" as userid
label "/user" as user

BlueBerryServer -. material
material -.> MaterialController::Get 

BlueBerryServer -. tag
tag -.> TagController::Get


BlueBerryServer -. userid
userid -.> UserController::Get   
userid -.> UserController::UpdateTags

@enduml
