@startuml
node ":UserMachine" <<device>> {
     component ":BlueberryClient" as client
}

node ":Server" <<container>> {
     component ":API Routing" as api
     component ":Materials" as materials
     component ":Users" as users
     component ":Tags" as tags
     component ":Search" as search
}

database ":Database" <<container>> as db
cloud ":Authentication" <<service>> as auth



client -.> api
api -.> search
api -.> users
api -.> tags

search -.> materials
search -.> users


materials -.> tags
users -.> tags
materials -.> db
tags -.> db
users -.> db

client -left.> auth
api -.> auth

@enduml

