@startuml

actor User as user
control Search as search
entity User as userInformation
entity  Repository as repository
actor Database as database

user -> search : activate search function
activate user

activate search

search -> userInformation : read user information
activate userInformation
userInformation -> search : return user user information
deactivate userInformation


search -> repository : request materials
activate repository

repository -> database : select materials
activate database
database -> repository : return materials
deactivate database

repository -> search : return materials
deactivate repository

search -> user : display results 
deactivate search
deactivate user

@enduml
