@startuml
participant Client
Participant "API Routing" as API

Client ->> API: request(searchParameters)
activate API

API ->> Search: search(options)
activate Search

Search -> Database: get(materials)
activate Database
Database -->> Search
deactivate Database

Search -->> API
deactivate Search

API -> Client: reply(searchResults)
deactivate API

@enduml

