@startuml

package "Client"
cloud Authentication
database Database

package "Server" {
    [Core]
    [API]
    component "Infrastructure" {
        [Database] as InfDb
        [Authentication] as InfAuth
    }
    component "Services" {
        [Search]
        [User]
    }
}

Client .down.> API

API ..> Services
Services ..> Infrastructure

Authentication .left.> InfAuth
Database .up.> InfDb

Infrastructure ..> Core
Services ..> Core

@enduml
