@startuml

package Client

package Server {
  component Tags {
    component Tag
    component "Tag Repository" as TagRepo
  }

  component Search

  component Materials {
    component Material
    component "Material Repository" as MatRepo
  }

  component Users {
    component User
    component "User Repository" as UserRepo
  }

  component "API Routing" as API
}

cloud Database
cloud "Authentication Provider" as Auth

Client .down.> API

TagRepo ..> Tag
TagRepo ..> Database

UserRepo ..> User
UserRepo ..> Auth
UserRepo ..> Database

MatRepo ..> Material
MatRepo ..> Tag
MatRepo ..> Database

Search ..> MatRepo
Search ..> UserRepo
Search ..> Material

API ..> Search
API ..> TagRepo
API ..> UserRepo

@enduml

