@startuml
left to right direction
actor "User" as user
actor "Guest" as guest
rectangle Blueberry {
  usecase "Create User" as create
  usecase "Login" as login
  usecase "Logout" as logout
  usecase "Search" as search
  usecase "SearchWithWords" as filter
  usecase "SearchWithFilters" as unfilter
}
usecase "Authentication" as auth

user --> login
user --> logout
login -up.> auth : include

user --> search
search <|-- filter
search <|-- unfilter

filter <.> unfilter : extends 

guest --> create
@enduml
