global using Xunit;
global using System;
global using System.Threading.Tasks;
global using System.Collections.Generic;
global using blueberry.Core;
global using Microsoft.Data.Sqlite;
global using Microsoft.EntityFrameworkCore;
global using static blueberry.Core.Status;
global using blueberry.Infrastructure;
global using blueberry.Common;
